### ISSUE TITLE
Apps-generated tokens doesn't give full access to GraphQL queries/mutations

### ISSUE THREAD

**Issue by Yegabebar** [mirumee/saleor-platform#100]
Hey everyone,
We are trying to use GraphQL mutations to get and add data to the database but we keep getting "You do not have permission to perform this action", even with a token generated from an app in the dashboard.
We use Saleor-platform v2.11, the tokens we use should have full access to the store so we don't know what to do now...
Is it a known issue?
How can we bypass this problem?
Thanks!

**Comment by Yegabebar** [comment]
```
{
  "errors": [
    {
      "message": "You do not have permission to perform this action",
      "locations": [
        {
          "line": 2,
          "column": 3
        }
      ],
      "path": [
        "customers"
      ],
      "extensions": {
        "exception": {
          "code": "PermissionDenied",
          "stacktrace": [
            "Traceback (most recent call last):",
            "  File \"/usr/local/lib/python3.8/site-packages/promise/promise.py\", line 489, in _resolve_from_executor",
            "    executor(resolve, reject)",
            "  File \"/usr/local/lib/python3.8/site-packages/promise/promise.py\", line 756, in executor",
            "    return resolve(f(*args, **kwargs))",
            "  File \"/usr/local/lib/python3.8/site-packages/graphql/execution/middleware.py\", line 75, in make_it_promise",
            "    return next(*args, **kwargs)",
            "  File \"/app/saleor/graphql/core/fields.py\", line 164, in connection_resolver",
            "    iterable = resolver(root, info, **args)",
            "  File \"/app/saleor/graphql/decorators.py\", line 15, in wrapper",
            "    return func(info.context, *args, **kwargs)",
            "  File \"/app/saleor/graphql/decorators.py\", line 31, in wrapper",
            "    raise PermissionDenied()",
            "saleor.core.exceptions.PermissionDenied: You do not have permission to perform this action"
          ]
        }
      }
    }
  ],
  "data": {
    "customers": null
  }
}
```

**Comment by krzysztofwolski** [comment]
https://docs.saleor.io/docs/3.0/developer/users#authentication

Are you adding auth headers to the request in proper format? ie:
```
{
  "Authorization": "Bearer APPTOKEN"
}
```

**Comment by Yegabebar** [comment]
Hello @krzysztofwolski, 
Thanks for the reply.
Yes, this is how my headers look like in the GQL playground. 
I tried with 'token', saleor says the user is anonymous when I use this one.
I get the permission error when I use 'crsfToken', so I guess this is the one I need to use.

I wonder if there's a problem in the way saleor checks the current user's permissions, but in the meantime everything seems to work when I log in with the same user in the dashboard...
I'm trying to see if there's a problem in saleor but it's a bit complicated with the dev skills I have as of today :)

**Comment by Yegabebar** [comment]
Ok so in fact I didn't use a correct header...
It works better that way:
```
{
  "Authorization": "JWT <Token>"
}
```
I was using Bearer instead of JWT with the csrfToken but actually the right mix seems to be "JWT MyToken".
