### ISSUE TITLE
Retrieving a warehouse with a query in graphql playground

### ISSUE THREAD

**Issue by sourcesolver** [mirumee/saleor-platform#103]
I'm using graphql playrgound to explore things. I don't see this in the docs: can you tell me how I could form a query to retrieve the names of all my warehouses; and then maybe each of their inventory??

I can do, for example, "{warehouses {totalCount}}" and get back:

{"data": {"warehouses": {"totalCount": 1}}}

but some names and inventory would be a query I imagine many would like to do...

**Comment by sourcesolver** [comment]
???

https://media.giphy.com/media/5x89XRx3sBZFC/source.gif

**Comment by sourcesolver** [comment]
???

![tumbleweed](https://user-images.githubusercontent.com/80441845/123338942-a7bbd100-d517-11eb-99f3-e9eab5d3e3b4.gif)

**Comment by maarcingebala** [comment]
You can fetch the list of warehouses using this query:

```graphql
{
  warehouses(first: 5) {
    edges {
      node {
        name
      }
    }
  }
}
```
Note that this query is only available to admins; you need to be an authenticated user with either `MANAGE_PRODUCTS`, `MANAGE_ORDERS` or `MANAGE_SHIPPING` permission to access it). [See the docs page about authentication in API](https://docs.saleor.io/docs/3.0/developer/users#authentication).

Stock quantities are available through particular ProductVariant objects:

```graphql
{
  product(slug: "black-hoodie") {
    variants {
      sku
      quantityAvailable
      stocks {
        warehouse {
          name
        }
        quantity
        quantityAllocated
      }
    }
  }
}
```
`quantityAvailable` will give you total quantity, but you can also provide an address to get quantity from a particular warehouse that ships to that address. There is also `stocks` field with accurate quantities in each warehouse but again, this field is restricted to admin. See the docs: https://docs.saleor.io/docs/3.0/developer/products#stock-quantities

**Comment by sourcesolver** [comment]
Thank you very much for the response! I have a two-week deadline for another project but will look into this once that is done.
