### ISSUE TITLE
The submodules are way too outdated and a word of caution!

### ISSUE THREAD

**Issue by brandnewx** [mirumee/saleor-platform#104]
The actual projects (saleor, saleor-storefront, saleor-dashboard) are up to date, running with latest Python, Node.js and npm packages, but this repo references to the outdated submodules dated 8 months ago!

This means that nobody should deploy this repo for production ever! You should instead pull repos individually and use the docker-compose.yml as reference.

Or you can update the submodules first before running _docker-compose build_

```
git submodule update --init --recursive

git submodule foreach 'git fetch origin; git checkout $(git rev-parse --abbrev-ref HEAD); git reset --hard origin/$(git rev-parse --abbrev-ref HEAD); git submodule update --recursive; git clean -dfx'

git submodule update --recursive --remote --merge

git add . && git commit -m 'Update submodules to latest revisions'
```
Then you can continue with _docker-compose build_

**Comment by sin-ack** [comment]
>This means that nobody should deploy this repo for production ever!

Yes. From the README: 
> Keep in mind this repository is for local development only and is not meant to be deployed on any production environment! If you're not a developer and just want to try out Saleor you can check our live demo.

**Comment by brandnewx** [comment]
That's the issue. Dev setup is usually with the latest dependencies not with old, stale dependencies.

I think this repo is getting a demo up and running, however old the demo is.
