### ISSUE TITLE
Release policy

### ISSUE THREAD

**Issue by PiotrLaszczyk** [mirumee/saleor-platform#15]
Could You add some tag versioning for saleor-platform.
I'm looking for stable version of: saleor + dashboard + storefront.

**Comment by maarcingebala** [comment]
As described in issue #5, we will do so when we release new versions of all these three components. The exact release date is not agreed on yet, but I suppose it will be in one or two months from now.

**Comment by PiotrLaszczyk** [comment]
Ok, but for now. What are best versions of all three components that works together?

I spend some time playing with that and have some problems to get all three working together.

**Comment by xavitorne** [comment]
> Ok, but for now. What are best versions of all three components that works together?
> 
> I spend some time playing with that and have some problems to get all three working together.

same for me, i have some doubts about the versions of the components to use, I tried but I have problems using the stable version of the frontend. Thanks

**Comment by maarcingebala** [comment]
As for now, the latest versions that can be used together are:
- Saleor - 2.9.1
- Storefront - 0.7.0
- Dashboard - 2.0.0

In future releases, we want to unify the versioning to make it easier to understand which versions can be run together.

**Comment by maarcingebala** [comment]
Closing this in favor of #5.
