### ISSUE TITLE
Issue cloning repository

### ISSUE THREAD

**Issue by gabernalt** [mirumee/saleor-platform#16]
**What I'm trying to achieve**

Run Saleor using saleor-platform project on Docker-compose

**Steps to reproduce the problem**

1. Successfully installed Docker and Docker-compose
2. Checked that my github account has a SSH key installed and running
3. Run git clone git@github.com:mirumee/saleor-platform.git --recursive --jobs 3 according to the instructions in https://github.com/mirumee/saleor-platform

** I have previously cloned each Saleor component individually following the documentation https://docs.saleor.io/docs/next/getting-started/installation-windows/

**What I expected to happen**

Successfully cloning saleor-platform, saleor, saleor-storefront and saleor-dashboard

**Log**

(Saleor4) C:\Users\Tavo\Dev\Saleor4>git clone git@github.com:mirumee/saleor-platform.git --recursive --jobs 3
fatal: destination path 'saleor-platform' already exists and is not an empty directory.

(Saleor4) C:\Users\Tavo\Dev\Saleor4>git clone git@github.com:mirumee/saleor-platform.git --recursive --jobs 3
Cloning into 'saleor-platform'...
Enter passphrase for key '/c/Users/Tavo/.ssh/id_rsa':
remote: Enumerating objects: 91, done.
remote: Counting objects: 100% (91/91), done.
remote: Compressing objects: 100% (65/65), done.
Receiving objects:  40% (37/91)47), reused 50 (delta 26), pack-reused 0
Receiving objects: 100% (91/91), 36.66 KiB | 102.00 KiB/s, done.
Resolving deltas: 100% (47/47), done.
Submodule 'saleor' (git@github.com:mirumee/saleor.git) registered for path 'saleor'
Submodule 'saleor-dashboard' (git@github.com:mirumee/saleor-dashboard.git) registered for path 'saleor-dashboard'
Submodule 'saleor-storefront' (git@github.com:mirumee/saleor-storefront.git) registered for path 'saleor-storefront'
Cloning into 'C:/Users/Tavo/Dev/Saleor4/saleor-platform/saleor'...
git@github.com: Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
fatal: clone of 'git@github.com:mirumee/saleor.git' into submodule path 'C:/Users/Tavo/Dev/Saleor4/saleor-platform/saleor' failed
Failed to clone 'saleor'. Retry scheduled
Cloning into 'C:/Users/Tavo/Dev/Saleor4/saleor-platform/saleor-dashboard'...
git@github.com: Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
fatal: clone of 'git@github.com:mirumee/saleor-dashboard.git' into submodule path 'C:/Users/Tavo/Dev/Saleor4/saleor-platform/saleor-dashboard' failed
Failed to clone 'saleor-dashboard'. Retry scheduled
Cloning into 'C:/Users/Tavo/Dev/Saleor4/saleor-platform/saleor-dashboard'...
git@github.com: Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
fatal: clone of 'git@github.com:mirumee/saleor-dashboard.git' into submodule path 'C:/Users/Tavo/Dev/Saleor4/saleor-platform/saleor-dashboard' failed
Failed to clone 'saleor-dashboard' a second time, aborting
Cloning into 'C:/Users/Tavo/Dev/Saleor4/saleor-platform/saleor-storefront'...
git@github.com: Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
fatal: clone of 'git@github.com:mirumee/saleor-storefront.git' into submodule path 'C:/Users/Tavo/Dev/Saleor4/saleor-platform/saleor-storefront' failed
Failed to clone 'saleor-storefront'. Retry scheduled
Cloning into 'C:/Users/Tavo/Dev/Saleor4/saleor-platform/saleor'...
git@github.com: Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
fatal: clone of 'git@github.com:mirumee/saleor.git' into submodule path 'C:/Users/Tavo/Dev/Saleor4/saleor-platform/saleor' failed
Failed to clone 'saleor' a second time, aborting
Cloning into 'C:/Users/Tavo/Dev/Saleor4/saleor-platform/saleor-storefront'...
git@github.com: Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
fatal: clone of 'git@github.com:mirumee/saleor-storefront.git' into submodule path 'C:/Users/Tavo/Dev/Saleor4/saleor-platform/saleor-storefront' failed
Failed to clone 'saleor-storefront' a second time, aborting

**System information**
Operating system: Windows 10
Python 3.8.1
Node.js version 12.14.1
PostreSQL 10.12
GTK3+ for Win64
Build Tools 2017 v 14.24

**Comment by maarcingebala** [comment]
Hey, I'm not sure what is the issue exactly. The first error says that "fatal: destination path 'saleor-platform' already exists and is not an empty directory." - maybe you could try to delete all the related Saleor catalogs and try to clone the platform again?

There is also a second error about permissions. Maybe there's some issue with setting up your public SSH key? Maybe this Github article could help: https://help.github.com/en/github/authenticating-to-github/error-permission-denied-publickey

**Comment by keeganlegg** [comment]
I had a similar issue with permission problems. **Starting the ssh-agent server and adding the key solved the issue**. I already had the key added to my Github account, but manually typing the password multiple times was causing issues I guess.

**Comment by gabernalt** [comment]
Yeah, I found it easier just to clone the repository with the Git GUI to avoid any issues with my existing SSH key and ssh-agent

**Comment by NyanKiyoshi** [comment]
Related to https://github.com/mirumee/saleor-platform/issues/19.

**Comment by Eiarzate1** [comment]
In case you don't want to download any additional GUI tools follow steps described here to generate SSH private and public key:

https://help.github.com/en/github/authenticating-to-github/generating-a-new-ssh-key-and-adding-it-to-the-ssh-agent

Secondly add ssh public key to your github account with instructions from here:
https://help.github.com/en/github/authenticating-to-github/adding-a-new-ssh-key-to-your-github-account

**Comment by Cloud-Forge** [comment]
An other easy solution instead of messing with keys...

### To force https instead of git

    git config --global url."https://github.com/".insteadOf git@github.com:
    git config --global url."https://".insteadOf git://

### To force git instead of https

    git config --global url."git@github.com:".insteadOf https://github.com/
    git config --global url."git://".insteadOf https://
