### ISSUE TITLE
Add note about required SSH keys 

### ISSUE THREAD

**Issue by maarcingebala** [mirumee/saleor-platform#17]
To successfully clone and run the platform user need to have SSH keys configured on Github. We should mention that as a prerequisite in the readme with links to Github help pages:
- https://help.github.com/en/github/authenticating-to-github/generating-a-new-ssh-key-and-adding-it-to-the-ssh-agent
- https://help.github.com/en/github/authenticating-to-github/adding-a-new-ssh-key-to-your-github-account

**Comment by NyanKiyoshi** [comment]
Wouldn't people using Git know that and already have one set-up?

Maybe just a very small note...

```markdown
_Note if you get permission denied, make sure you have [set-up SSH access in your GitHub account](https://help.github.com/en/github/authenticating-to-github/adding-a-new-ssh-key-to-your-github-account)_
```

I really would expect most users to have this done already (maybe Windows users are more likely to run into this issue as it seems a lot of them are using HTTPS instead of SSH).

**Comment by maarcingebala** [comment]
That's also what I expected, but we're already getting issues and questions about problems with cloning the repo related to missing SSH setup. So we can make their life easier (hopefully) and provide an information about this.

**Comment by NyanKiyoshi** [comment]
Super-seeded by https://github.com/mirumee/saleor-platform/issues/19.
