### ISSUE TITLE
Remove default SSH in favor of HTTPS

### ISSUE THREAD

**Issue by NyanKiyoshi** [mirumee/saleor-platform#19]
We noticed that some users were facing issues when trying to clone and fetch anonymously or without SSH and GitHub configured together because of SSH being enforced in the sub-modules.

We decided to remove SSH altogether in favor of HTTPS to permit anonymous access for automatic cloning (CI, scripts) and users having no prior configurations or using HTTPS instead of SSH on GitHub. It also makes it harder and is confusing users that are not familiar with git and SSH.

Users wanting SSH to gain write access through GitHub authentication can alter the remotes themselves which is straightforward for users that are familiar with git.

TBD:
- Alter the git sub-modules configuration file
- Alter the README

**Comment by bazaihenxian** [comment]
is there anyone who can review the request? I really need submodules to be https instead of ssh

**Comment by maarcingebala** [comment]
Fixed in #58.
