### ISSUE TITLE
Got error when run docker-compose build

### ISSUE THREAD

**Issue by IEB-Richard** [mirumee/saleor-platform#26]
I got the following error when run docker-compose build command:

```
Thank you for using core-js ( https://github.com/zloirock/core-js ) for polyfilling JavaScript standard library!

The project needs your help! Please consider supporting of core-js on Open Collective or Patreon:
> https://opencollective.com/core-js
> https://www.patreon.com/zloirock

Also, the author of core-js ( https://github.com/zloirock ) is looking for a good job -)


> cwebp-bin@5.0.0 postinstall /app/node_modules/cwebp-bin
> node lib/install.js

  ⚠ connect ECONNREFUSED 0.0.0.0:443
  ⚠ cwebp pre-build test failed
  ℹ compiling from source
  ✔ cwebp built successfully

> gifsicle@4.0.1 postinstall /app/node_modules/gifsicle
> node lib/install.js

  ⚠ connect ECONNREFUSED 0.0.0.0:443
  ⚠ gifsicle pre-build test failed
  ℹ compiling from source
  ✔ gifsicle built successfully

> mozjpeg@6.0.1 postinstall /app/node_modules/mozjpeg
> node lib/install.js

  ⚠ connect ECONNREFUSED 0.0.0.0:443
  ⚠ mozjpeg pre-build test failed
  ℹ compiling from source
```

**Comment by NyanKiyoshi** [comment]
@IEB-Richard that's not an error? What is wrong?

**Comment by emilepetrone** [comment]
@NyanKiyoshi I was able to get the installation to complete. I think @IEB-Richard and I both were just shocked to hit a `command failed` before it ultimately succeeded.

**Comment by NyanKiyoshi** [comment]
Ah okay. So @IEB-Richard might have forgot to include the whole output.
That's odd, sounds like the image is missing `mesa-dev`.

**Comment by IEB-Richard** [comment]
Sorry. This is not an error. I finally got it to build successfully. 
@emilepetrone thanks! yes, exactly! 
I am still facing some registry issues to get the server up. I think it may be the internet access issue, as I am working from China. I will open another issue if I cannot figure out a solution by myself.

**Comment by NyanKiyoshi** [comment]
@emilepetrone platform? OS and Processor

**Comment by david-daming** [comment]
@IEB-Richard ,
I am working on my new Macbook Pro 16 Inc, with 64G ram, I still meet the same issue. 

I found my docker default memory to 2GB, after I updated my CPU to 8, memory to 16GB, after the change, docker will be start automatically, then I can easily start the server without any issue.

You change assign more system resources by changing docker -> Preference -> Resources -> Advanced.

**Comment by balibebas** [comment]
Saw this during initial platform setup. Looks like a non-issue though as `cwebp` eventually builds regardless.

<img width="836" alt="Screen Shot 2020-09-05 at 23 16 54" src="https://user-images.githubusercontent.com/65664227/92308146-2a49c300-efce-11ea-90bd-1d975280de6f.png">

macOS Big Sur 11.0 Beta (20A5354i)
Docker version 19.03.12, build 48a66213fe
