### ISSUE TITLE
Error during docker-compose

### ISSUE THREAD

**Issue by srendon** [mirumee/saleor-platform#33]
Hi Saleor team, I'm having problem when doing the command `docker-compose build` there is this error: 
```
 ⚠ Command failed: /app/node_modules/cwebp-bin/vendor/cwebp -version
/app/node_modules/cwebp-bin/vendor/cwebp: error while loading shared libraries: libGL.so.1: cannot open shared object file: No such file or directory


  ⚠ cwebp pre-build test failed
  ℹ compiling from source
  ✔ cwebp built successfully
```
Then if migrations are executes (`docker-compose run --rm api python3 manage.py migrate`) there is the next error: `Error response from daemon: error evaluating symlinks from mount source "/host_mnt/d/.../saleor-platform/saleor/templates": lstat /host_mnt: function not implemented`

**Comment by NyanKiyoshi** [comment]
Operating system?

**Comment by srendon** [comment]
I'm using Windows 10 Pro Version 1909. For Docker is version 2.3.0.2

**Comment by srendon** [comment]
Hey @NyanKiyoshi I just did the same commands on Ubuntu 18.04 and same error.

**Comment by tomaszszymanski129** [comment]
Hi @srendon, apparently it's a bug in docker, could you try downgrading docker to 2.2.0.5 as they suggested here? https://github.com/docker/for-win/issues/6634

**Comment by srendon** [comment]
Hi @tomaszszymanski129 it worked. Thank you for your help!

**Comment by balibebas** [comment]
For the record Issue occurs on macOS Big Sur using docker 19 though this appears to be a duplicate of https://github.com/mirumee/saleor-platform/issues/26 which is also closed.

**Comment by NyanKiyoshi** [comment]
@balibebas can you open a new issue about it? I'm guessing this is storefront failing? Meantime you open an issue, try adding this to the failing dockerfile:
```dockerfile
RUN apt update && apt install -y --no-install-recommends libgl1 && rm -rf /var/lib/apt/lists/*
```

This will install the [missing library](https://packages.ubuntu.com/focal/amd64/libgl1/filelist).

**Comment by balibebas** [comment]
> I'm guessing this is storefront failing?

Storefront works just fine. I left an update in #26 to that regard. Given there are already two issues, my recommendation would be to reuse one of those instead of creating a new issue if there's anything actionable. Otherwise keeping these two issues unlocked so others can chime in ought to be good enough.

As for the ENV vars mentioned, I'll give that a try when I can. Thank you for the tip.
