### ISSUE TITLE
How does one production a fork of this project ? [help] [support]

### ISSUE THREAD

**Issue by superciccio** [mirumee/saleor-platform#48]
Hello,

great job building this project.

What's missing for production ? and what file/config do I have to change it ?

thanks for the help :)

**Comment by maarcingebala** [comment]
Hey, the `saleor-platform` project is meant for local development only. In production, you need to separately deploy the backend and frontend clients.

**Comment by superciccio** [comment]
Hi,
What I meant was a different thing. sorry for the misunderstanding...

Do I need to create a redis imagine and postgresql as well and then change the endpoint in docker ?

I was looking more for this kind of infos...

Thaks

**Comment by NyanKiyoshi** [comment]
You can also extend the docker image.

```dockerfile
ARG VERSION="f354d5b80f0924dac6c8b7d5851995ddbfb48a22"
FROM mirumee/saleor:${VERSION}
```

For Redis, it depends. Redis will only be used for Celery tasks, if you are on AWS for example, it would be way cheaper to go for a SQS queue.

**Comment by superciccio** [comment]
ah, interesting...
thanks :)
I guess we can close this issue. I've something in mind for what do next, much appreciated !
