### ISSUE TITLE
Saleor platform contains unstable subprojects releases

### ISSUE THREAD

**Issue by tomaszszymanski129** [mirumee/saleor-platform#5]
For now the repository contains changes implemented after 2.9.1 because these contains dev dockerfiles for dashboard and storefront. It wouldn't work otherwise and we believe it would be for the best if by default it contains stable releases.

This is a reminder ticket - repository subprojects should be updated when we release a version newer than 2.9.1

Also readme should be updated - section "How to update the subprojects to the newest versions?"

**Comment by NyanKiyoshi** [comment]
Isn't this already done?
